#!/bin/sh

# Save latest commit's hash
# Check if dir is empty (so there is no commits yet)
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    head=$(git rev-parse HEAD)
else
    head=''
fi

if [ ! -d '.githooks' ]; then
    mkdir .githooks
fi

echo $head > .githooks/head
