" Basic settings {{{
    " Disable compatible mod with vi
    set nocompatible

    " Syntax highliting
    syntax enable

    " Configure lines
    set number
    set relativenumber
    set ruler

    " Set encodings 
    set encoding=utf-8
    set fileencodings=utf-8,cp1251

    " Tabs and etc
    set tabstop=4
    set shiftwidth=4
    set smarttab
    set expandtab

    " Indention
    set smartindent

    " File type
    filetype on
    filetype indent on

    " Search
    set incsearch
    set smartcase

    " Swap-file directory
    set directory=/tmp//
    " Backup-file directory
    set backupdir=/tmp//
    " Undo-file directory
    set undodir=/tmp//
    
    " Show command
    set showcmd

    " No beep. Only visualbells
    " set visualbell

    " Fuzzy File Search
    set path+=**
    set wildmenu

    " File browsing
    let g:netrw_banner=0        " disable annoying banner
    let g:netrw_browse_split=4  " open in prior window
    let g:netrw_altv=1          " open splits to the right
    let g:netrw_liststyle=3     " tree view

    " Russian keyboard
    set keymap=russian-jcukenwin
    set iminsert=0
    set imsearch=0
    highlight lCursor guifg=NONE guibg=Cyan
" }}}

" Mappings {{{
    " Map leader
    let mapleader = "-"
    let maplocalleader = ","

    " Help navigation
    " Jump to topic under the cursor
    nnoremap <cr> <c-]>
    " Jump back
    nnoremap <BS> <c-o>

    " Stop highlighting items from last search
    nnoremap <leader>nh :nohlsearch<cr>

    " Folding
    nnoremap <space> za

    " Edit my .vimrc and source it
    nnoremap <leader>ev :edit $MYVIMRC<cr>
    nnoremap <leader>sv :source $MYVIMRC<cr>

    " Move to start or end of line
    nnoremap <leader>H H
    nnoremap <leader>L L

    " Set cursor to the beggining of the current line
    nnoremap H I<esc>
    nnoremap L A<esc>

    " Yank from the cursor to the EOL
    nnoremap Y y$

    " Tag jumping (ctags needed)
    command! MakeTags !ctags -R .

    " Insert HTML template
    nnoremap <leader>html :-1read $HOME/.vim/skeleton.html<CR>

    " Convert current word to uppercase in insert mode
    nnoremap <c-u> viwUe
    inoremap <c-u> <esc>viwUei

    " Put word under cursor in 
    " double quotes
    nnoremap <leader>" viw<esc>a"<esc>bi"<esc>lel
    " single quotes
    nnoremap <leader>' viw<esc>a'<esc>bi'<esc>lel

    " Exit insert mode with jk
    inoremap jk <esc>

" }}}

" Vim {{{
augroup type_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END
" }}}

" HTML {{{
augroup type_html
    autocmd!
    autocmd BufWritePre,BufRead *.html normal gg=G
    autocmd BufNewFile,BufRead *.html setlocal nowrap
    autocmd FileType html setlocal foldmethod=indent
augroup END
" }}}

" Python {{{
augroup type_py
    autocmd!
    " Comment line
    autocmd FileType python nnoremap <buffer> <localleader>c I#<space><esc>
    " Fold method
    autocmd FileType python setlocal foldmethod=indent
    " Snippets {{{
        " Func 
        autocmd FileType python iabbrev <buffer> deff def():<cr>pass<up><left><left><left>
        " If 
        autocmd FileType python iabbrev <buffer> iff if:<left>
        " Elif 
        autocmd FileType python iabbrev <buffer> eli elif:<left>
        " Else 
        autocmd FileType python iabbrev <buffer> ell else:<left>
        " While 
        autocmd FileType python iabbrev <buffer> whh while:<left>
        " Return 
        autocmd FileType python iabbrev <buffer> rett return
        " Class
        autocmd FileType python iabbrev <buffer> classs class:<cr>pass<up><left>
    " }}}
augroup END
" }}}

" C/C++ {{{
augroup type_c/cpp
    autocmd!
    " Comment line
    autocmd FileType c,c++ nnoremap <buffer> <localleader>c I//<space><esc>
    " Fold method
    autocmd FileType c,c++ setlocal foldmethod=indent
    " Snippets {{{
        " If 
        autocmd FileType c,c++ iabbrev <buffer> iff if ()<left>
        " Else if 
        autocmd FileType c,c++ iabbrev <buffer> eli else if ()<left>
        " Else 
        autocmd FileType c,c++ iabbrev <buffer> ell else ()<left>
        " While 
        autocmd FileType c,c++ iabbrev <buffer> whh while ()<left>
        " Return 
        autocmd FileType c,c++ iabbrev <buffer> rett return
    " }}}
augroup END
" }}}

" JavaScript {{{
augroup type_javascript
    autocmd!
    " Comment line
    autocmd FileType javascript nnoremap <buffer> <localleader>c I//<space><esc>
    " Indentation
    autocmd FileType javascript setlocal tabstop=2
    autocmd FileType javascript setlocal shiftwidth=2
    " Fold method
    autocmd FileType javascript setlocal foldmethod=indent
    " Snippets {{{
        " If 
        autocmd FileType javascript iabbrev <buffer> iff if ()<left>
        " Else if 
        autocmd FileType javascript iabbrev <buffer> eli else if ()<left>
        " Else 
        autocmd FileType javascript iabbrev <buffer> ell else ()<left>
        " While 
        autocmd FileType javascript iabbrev <buffer> whh while()<left>
        " Return 
        autocmd FileType javascript iabbrev <buffer> rett return
    " }}}
augroup END
" }}}
